### ISSUE TITLE
Kaniwani Companion

### ISSUE THREAD

**Issue by DJTB** [naei/wanikani-companion#4]
Hi Naei, 

I'm one of the devs on [Kaniwani](http://kaniwani.com) and was going to modify my local Wanikani Companion to show me next review times for both WK and KW in the dropdown.

When I'm finished - do you mind if I share the fork with others on WK? Alternatively - I could add a checkbox to settings, and you could merge it and include it as part of the chrome version (so users can opt in to the extra functionality - it would be turned off by default).

I won't be working on it straight away; figured I'd check with you to see what you think first.

**Comment by naei** [comment]
Hello Duncan,

Sure you can share your fork with anyone.
In order to keep a lightweight interface, I would prefer to keep WK Companion only for WaniKani, but it would be great to have a dedicated KaniWani Companion extension including all the KW features! In that way people should be able to add and use the WK and KW Companion together, as dedicated Chrome extensions. If you like this idea, feel free to adapt my code for KaniWani and publish your own extension.

**Comment by DJTB** [comment]
That sounds sensible, I'll make a fork and drop it onto the forums when it's ready.
Thanks for sharing!

**Comment by naei** [comment]
Great, I'm looking forward to take a look at it!
