### ISSUE TITLE
Can't do lessons or reviews

### ISSUE THREAD

**Issue by ericellingson** [naei/wanikani-companion#7]
The main page which shows the number of available lessons and reviews is fine, but once clicked on (either one), nothing loads. The following error is logged to the console: Refused to display 'https://www.wanikani.com/review/session' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by naei** [comment]
Thank you for having noticed this!
This issue was fixed a month ago with the 1.2.4.3 release, but for some reason this version wasn't released on the Chrome Web Store. I just published it again.
If your Wanikani Companion client doesn't automatically update to version 1.2.4.3, you can try to remove and reinstall the app. Otherwise, you can also directly run it [from the source](https://github.com/naei/wanikani-companion#installation).

**Comment by ericellingson** [comment]
Awesome! I just got a notification about new permissions, and it resolved the issue. Thanks
